name = "RegularRegistry"
uuid = "652f5ff9-c646-421d-ab62-7f2a7322f5fc"
repo = "git@github.com:aeyobd/RegularRegistry.git"

[packages]
1391d4f3-b950-46e7-ae93-86515cdc2b0b = { name = "LilGuys", path = "L/LilGuys" }
415bc928-4679-4905-9aff-233f9524af88 = { name = "Arya", path = "A/Arya" }
6a64a12f-920b-4cea-9d97-f6c2170ce0ee = { name = "DensityEstimators", path = "D/DensityEstimators" }
8bc99c6c-7bfa-45ed-8c8b-4447c0025491 = { name = "PyFITS", path = "P/PyFITS" }
c9d1a974-9120-43da-b5b1-d69fd551855f = { name = "Agama", path = "A/Agama" }
